coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0%
        base: auto
        if_not_found: success
        informational: false
        only_pulls: false
        if_ci_failed: success
